spring:
  config:
    activate:
      on-profile: test
name: test-YAML
environment: testing
enabled: false
server:
  port: 4000
welcomeMsg: "Hello from Test"

---
spring:
  config:
    activate:
      on-profile: prod
name: prod-YAML
environment: production
enabled: true
server:
  port: 5000
welcomeMsg: "Hello from Prod"

